#!/bin/bash
export PATH=/net/alruba2.uio.no/mn/alruba2/astro/local/opt/intel/oneapi/compiler/2022.2.0/linux/bin/intel64:/net/alruba2.uio.no/mn/alruba2/astro/local/opt/intel/oneapi/mpi/2021.7.0/libfabric/bin:/net/alruba2.uio.no/mn/alruba2/astro/local/opt/intel/oneapi/mpi/2021.7.0/bin:/mn/stornext/u3/sigurdkn/local/moduledata/python3.10/bin:/mn/stornext/u3/jonassl/local/bin:/mn/stornext/u3/jonassl/.local/bin:/astro/local/opt/Intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin:/astro/local/opt/Intel/compilers_and_libraries_2020.4.304/linux/bin/intel64:/astro/local/opt/Intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/bin:/astro/local/opt/Intel/debugger_2020/gdb/intel64/bin:/usr/lib64/qt-3.3/bin:/astro/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lib64/openmpi/bin:/opt/dell/srvadmin/bin
echo "Running daily level1 rsync from OVRO at $(date)."
MONTH="$1"
DAY="$2"
rsync -Pavt --no-links comap_analysis@presto.caltech.edu:/comapdata*/pathfinder/level1/$MONTH*/comap-[0-9][0-9][0-9][0-9][0-9][0-9][0-9]-$DAY-[0-9][0-9][0-9][0-9][0-9][0-9].log /mn/stornext/d16/cmbco/comap/data/logs/presto_level1_logs/$MONTH
rsync -Pavt --no-links comap_analysis@presto.caltech.edu:/comapdata*/pathfinder/level1/$MONTH*/comap-[0-9][0-9][0-9][0-9][0-9][0-9][0-9]-$DAY-[0-9][0-9][0-9][0-9][0-9][0-9]_s1.hd5 /mn/stornext/d16/cmbco/comap/data/aux_data/tsys_presto/$MONTH
rsync --dry-run --info=name --archive --relative --no-implied-dirs --no-links comap_analysis@presto.caltech.edu:/comapdata*/pathfinder/level1/$MONTH*/comap-[0-9][0-9][0-9][0-9][0-9][0-9][0-9]-$DAY-[0-9][0-9][0-9][0-9][0-9][0-9].hd5 /mn/stornext/d16/cmbco/comap/data/level1/$MONTH/ > /mn/stornext/d16/cmbco/comap/data/level1/transfer_lists/l1_transfer_$DAY.log
sleep 2
cat /mn/stornext/d16/cmbco/comap/data/level1/transfer_lists/l1_transfer_$DAY.log | /astro/local/bin/parallel --will-cite -j 12 rsync -Pavt --no-links comap_analysis@presto.caltech.edu:/{} /mn/stornext/d16/cmbco/comap/data/level1/l1_temp/from_ovro/$MONTH/